version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: 'on'
    working_directory: /go/src/github.com/sambaiz/cdkbot
    steps:
      - checkout
      - run: make install-tools
      - run: make lint
      - run: make test